# Generated by Django 4.2.7 on 2023-11-14 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwappingProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('category', models.CharField(choices=[('Clothing', 'clothing'), ('Shoes', 'shoes')], max_length=20)),
                ('sex', models.CharField(choices=[('Women', 'women'), ('Man', 'man'), ('Kid', 'kid')], max_length=8)),
                ('size', models.CharField(choices=[('XS', 'xs'), ('S', 's'), ('M', 'm'), ('L', 'l'), ('XL', 'xl'), ('XXL', 'xxl')], max_length=3)),
                ('condition', models.CharField(choices=[('New', 'new'), ('As new', 'as new'), ('Very good condition', 'very good condition'), ('Good condition', 'good condition'), ('Fair condition', 'fair condition'), ('Worn', 'worn')], max_length=25)),
                ('color', models.CharField(choices=[('Black', 'black'), ('White', 'white'), ('Red', 'red'), ('Green', 'green'), ('Blue', 'blue'), ('Yellow', 'yellow'), ('Orange', 'orange'), ('Pink', 'pink'), ('Purple', 'purple'), ('Brown', 'brown'), ('Silver', 'silver'), ('Gold', 'gold')], max_length=20)),
                ('quality', models.CharField(choices=[('Poor', 'poor'), ('Low-quality', 'low-quality'), ('Good', 'good'), ('Excellent', 'excellent'), ('Luxurious', 'luxurious'), ('Custom-made', 'custom-made')], max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_reserved', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='images_article/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
