# Generated by Django 4.2.7 on 2023-11-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwappingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('category', models.CharField(choices=[('Clothing', 'clothing'), ('Shoes', 'shoes')], max_length=20)),
                ('sex', models.CharField(choices=[('Women', 'women'), ('Man', 'man'), ('Kid', 'kid')], max_length=8)),
                ('size', models.CharField(choices=[('XS', 'xs'), ('S', 's'), ('M', 'm'), ('L', 'l'), ('XL', 'xl'), ('XXL', 'xxl')], max_length=3)),
                ('product_condition', models.CharField(choices=[('New', 'new'), ('As new', 'as new'), ('Very good condition', 'very good condition'), ('Good condition', 'good condition'), ('Fair condition', 'fair condition'), ('Worn', 'worn')], max_length=25)),
                ('color', models.CharField(choices=[('Black', 'black'), ('White', 'white'), ('Red', 'red'), ('Green', 'green'), ('Blue', 'blue'), ('Yellow', 'yellow'), ('Orange', 'orange'), ('Pink', 'pink'), ('Purple', 'purple'), ('Brown', 'brown'), ('Silver', 'silver'), ('Gold', 'gold')], max_length=20)),
                ('quality', models.CharField(choices=[('Poor', 'poor'), ('Low-quality', 'low-quality'), ('Good', 'good'), ('Excellent', 'excellent'), ('Luxurious', 'luxurious'), ('Custom-made', 'custom-made')], max_length=20)),
            ],
        ),
    ]
